### ISSUE TITLE
Meta properties generator

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Brick#11]
Would be nice to implement a script that goes through your models and generates a code for the each property on it:

``` swift
import Brick

extension ViewModel {

  var metaId: Int? {
    set(value) {
      meta["id"] = value
    }
    get {
      return meta("id", type: Int.self)
    }
  }

  func metaId(value: Int) -> Int {
    return meta("id", value)
  }

  ///...
}
```

Then instead of "magic strings" you would use:

``` swift
viewModel.id = 11
viewModel.id(0) // => value to 0 by default
viewModel.id // optional value
```

**Comment by zenangst** [comment]
This would be ace! Bye bye magic strings, hello property safety. ⭐

**Comment by vadymmarkov** [comment]
@zenangst We went into another direction https://github.com/hyperoslo/Brick/pull/12 so this one can be closed.
